### ISSUE TITLE
Please explain the issue with Minishift's networking

### ISSUE THREAD

**Issue by gbraad** [projectodd/openwhisk-openshift#27]
In the README.md I find:
https://github.com/projectodd/openwhisk-openshift/blob/5deb4a2fff52a616713f38b0dc6354b8b2af89dc/README.md#L87-L88
Can you explain with this 'bug' is? I do not remember seeing an issue on our tracker for this...

**Comment by bbrowning** [comment]
I believe the ultimate upstream bug is https://github.com/openshift/origin/issues/12111 . That issue is also referenced by https://github.com/minishift/minishift/issues/1269 which describes a similar, albeit not identical situation. Those issues appear to be resolved now, so perhaps this is no longer needed?
